package main

import "github.com/ehmo/gum/internal/catalog"

// Calendar v3 OAuth scopes.
const (
	scopeCalendarReadonly = "https://www.googleapis.com/auth/calendar.readonly"
	scopeCalendarACL      = "https://www.googleapis.com/auth/calendar"
	scopeCalendarFreebusy = "https://www.googleapis.com/auth/calendar.readonly"
	scopeCalendarSettings = "https://www.googleapis.com/auth/calendar.settings.readonly"
	scopeCalendarEvents   = "https://www.googleapis.com/auth/calendar.events"
)

// BuildCalendarTierBOps returns the Tier B Calendar v3 surface beyond the
// three dispatch-curated ops (calendar.events.list/insert/update) and the
// existing calendarList.list. Spec §1.1 + §5.2: every Workspace service must
// expose CRUD coverage so BM25 search returns relevant ops for natural
// queries (gum-mwe acceptance: `gum search 'calendar freebusy'`).
//
// Coverage:
//   - events.{get,patch,delete,instances,move,quickAdd}
//   - calendars.{get,insert,update,patch,delete,clear}
//   - calendarList.{get,insert,update,patch,delete}
//   - acl.{list,get,insert,update,patch,delete}
//   - colors.get
//   - freebusy.query
//   - settings.{list,get}
func BuildCalendarTierBOps() []catalog.Op {
	return []catalog.Op{
		// ── events (additional) ──────────────────────────────────────────
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.events.get",
			variantID:  "calendar.v3.rest.events.get",
			title:      "Get a Calendar event",
			summary:    "Fetch a single event by id from the specified calendar.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/calendars/{calendarId}/events/{eventId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Events.Get",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.events.patch",
			variantID:  "calendar.v3.rest.events.patch",
			title:      "Patch a Calendar event",
			summary:    "Partial-update an existing event. Only fields included in the body are changed.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarEvents},
			httpMethod: "PATCH",
			httpPath:   "/calendar/v3/calendars/{calendarId}/events/{eventId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Events.Patch",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.events.delete",
			variantID:  "calendar.v3.rest.events.delete",
			title:      "Delete a Calendar event",
			summary:    "Permanently delete an event from the specified calendar.",
			service:    "calendar",
			riskClass:  catalog.RiskClassDestructive,
			scopes:     []string{scopeCalendarEvents},
			httpMethod: "DELETE",
			httpPath:   "/calendar/v3/calendars/{calendarId}/events/{eventId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Events.Delete",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.events.instances",
			variantID:  "calendar.v3.rest.events.instances",
			title:      "List recurring event instances",
			summary:    "List instances of a recurring event between optional time bounds.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/calendars/{calendarId}/events/{eventId}/instances",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Events.Instances",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.events.move",
			variantID:  "calendar.v3.rest.events.move",
			title:      "Move event to another calendar",
			summary:    "Move an event to a different calendar (organizer transfer).",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarEvents},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/calendars/{calendarId}/events/{eventId}/move",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Events.Move",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.events.quickAdd",
			variantID:  "calendar.v3.rest.events.quickAdd",
			title:      "Quick-add Calendar event from text",
			summary:    "Parse a free-form text string into an event (e.g. 'Lunch Tue 12pm').",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarEvents},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/calendars/{calendarId}/events/quickAdd",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Events.QuickAdd",
		}),
		// ── calendars CRUD ───────────────────────────────────────────────
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendars.get",
			variantID:  "calendar.v3.rest.calendars.get",
			title:      "Get a calendar's metadata",
			summary:    "Fetch metadata for the specified calendar (summary, timezone, location).",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/calendars/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Calendars.Get",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendars.insert",
			variantID:  "calendar.v3.rest.calendars.insert",
			title:      "Create a new calendar",
			summary:    "Create a secondary calendar owned by the authenticated user.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/calendars",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Calendars.Insert",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendars.update",
			variantID:  "calendar.v3.rest.calendars.update",
			title:      "Update a calendar",
			summary:    "Full replacement of a calendar's metadata.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "PUT",
			httpPath:   "/calendar/v3/calendars/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Calendars.Update",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendars.patch",
			variantID:  "calendar.v3.rest.calendars.patch",
			title:      "Patch a calendar",
			summary:    "Partial-update a calendar's metadata.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "PATCH",
			httpPath:   "/calendar/v3/calendars/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Calendars.Patch",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendars.delete",
			variantID:  "calendar.v3.rest.calendars.delete",
			title:      "Delete a calendar",
			summary:    "Permanently delete a secondary calendar (primary cannot be deleted).",
			service:    "calendar",
			riskClass:  catalog.RiskClassDestructive,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "DELETE",
			httpPath:   "/calendar/v3/calendars/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Calendars.Delete",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendars.clear",
			variantID:  "calendar.v3.rest.calendars.clear",
			title:      "Clear primary calendar events",
			summary:    "Delete all events from the primary calendar (the calendar itself is preserved).",
			service:    "calendar",
			riskClass:  catalog.RiskClassDestructive,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/calendars/{calendarId}/clear",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Calendars.Clear",
		}),
		// ── calendarList (additional) ────────────────────────────────────
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendarList.get",
			variantID:  "calendar.v3.rest.calendarList.get",
			title:      "Get calendar-list entry",
			summary:    "Get an entry from the authenticated user's calendar list.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/users/me/calendarList/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "CalendarList.Get",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendarList.insert",
			variantID:  "calendar.v3.rest.calendarList.insert",
			title:      "Subscribe to a calendar",
			summary:    "Add an existing calendar to the authenticated user's calendar list (subscribe).",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/users/me/calendarList",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "CalendarList.Insert",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendarList.update",
			variantID:  "calendar.v3.rest.calendarList.update",
			title:      "Update calendar-list entry",
			summary:    "Replace a calendar-list entry (color, summary override, notification settings).",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "PUT",
			httpPath:   "/calendar/v3/users/me/calendarList/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "CalendarList.Update",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendarList.patch",
			variantID:  "calendar.v3.rest.calendarList.patch",
			title:      "Patch calendar-list entry",
			summary:    "Partial-update a calendar-list entry.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "PATCH",
			httpPath:   "/calendar/v3/users/me/calendarList/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "CalendarList.Patch",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.calendarList.delete",
			variantID:  "calendar.v3.rest.calendarList.delete",
			title:      "Unsubscribe from a calendar",
			summary:    "Remove a calendar from the authenticated user's calendar list (unsubscribe). The underlying calendar is unaffected.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "DELETE",
			httpPath:   "/calendar/v3/users/me/calendarList/{calendarId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "CalendarList.Delete",
		}),
		// ── ACL ──────────────────────────────────────────────────────────
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.acl.list",
			variantID:  "calendar.v3.rest.acl.list",
			title:      "List Calendar ACL entries",
			summary:    "List the access-control rules attached to a calendar.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/calendars/{calendarId}/acl",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Acl.List",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.acl.get",
			variantID:  "calendar.v3.rest.acl.get",
			title:      "Get a Calendar ACL rule",
			summary:    "Get a single access-control rule by id.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/calendars/{calendarId}/acl/{ruleId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Acl.Get",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.acl.insert",
			variantID:  "calendar.v3.rest.acl.insert",
			title:      "Grant access on a Calendar",
			summary:    "Add an access-control rule to a calendar (share with user, group, or domain).",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/calendars/{calendarId}/acl",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Acl.Insert",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.acl.update",
			variantID:  "calendar.v3.rest.acl.update",
			title:      "Update a Calendar ACL rule",
			summary:    "Replace an access-control rule (e.g. change role from reader to writer).",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "PUT",
			httpPath:   "/calendar/v3/calendars/{calendarId}/acl/{ruleId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Acl.Update",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.acl.patch",
			variantID:  "calendar.v3.rest.acl.patch",
			title:      "Patch a Calendar ACL rule",
			summary:    "Partial-update an access-control rule.",
			service:    "calendar",
			riskClass:  catalog.RiskClassWrite,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "PATCH",
			httpPath:   "/calendar/v3/calendars/{calendarId}/acl/{ruleId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Acl.Patch",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.acl.delete",
			variantID:  "calendar.v3.rest.acl.delete",
			title:      "Revoke Calendar access",
			summary:    "Permanently remove an access-control rule from a calendar.",
			service:    "calendar",
			riskClass:  catalog.RiskClassDestructive,
			scopes:     []string{scopeCalendarACL},
			httpMethod: "DELETE",
			httpPath:   "/calendar/v3/calendars/{calendarId}/acl/{ruleId}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Acl.Delete",
		}),
		// ── colors + freebusy ────────────────────────────────────────────
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.colors.get",
			variantID:  "calendar.v3.rest.colors.get",
			title:      "Get Calendar color palette",
			summary:    "Return the set of color definitions for calendars and events.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarReadonly},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/colors",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Colors.Get",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.freebusy.query",
			variantID:  "calendar.v3.rest.freebusy.query",
			title:      "Query free/busy intervals",
			summary:    "Return free/busy intervals for a set of calendars over a time range.",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarFreebusy},
			httpMethod: "POST",
			httpPath:   "/calendar/v3/freeBusy",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Freebusy.Query",
		}),
		// ── settings ─────────────────────────────────────────────────────
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.settings.list",
			variantID:  "calendar.v3.rest.settings.list",
			title:      "List Calendar user settings",
			summary:    "Return the authenticated user's calendar settings (locale, timezone, etc.).",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarSettings},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/users/me/settings",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Settings.List",
		}),
		makeWorkspaceOp(workspaceOpSpec{
			opID:       "calendar.settings.get",
			variantID:  "calendar.v3.rest.settings.get",
			title:      "Get a single Calendar user setting",
			summary:    "Return a single named calendar setting (e.g. 'timezone').",
			service:    "calendar",
			riskClass:  catalog.RiskClassRead,
			scopes:     []string{scopeCalendarSettings},
			httpMethod: "GET",
			httpPath:   "/calendar/v3/users/me/settings/{setting}",
			goPkg:      "google.golang.org/api/calendar/v3",
			goCall:     "Settings.Get",
		}),
	}
}
