// gen_dispatch_stubs.go emits the per-variant stub files under gen/dispatch/.
//
// Spec §5.7 line 826: "Generated REST dispatch stubs in `gen/dispatch/*.go`
// MUST pass the incoming `context.Context` to the typed Google API call
// chain via `.Context(ctx)` before `.Do()`." The v0.1.0 stubs satisfy this by
// forwarding to internal/adapters.TypedRestSDK, which calls
// http.NewRequestWithContext(ctx, ...) verbatim. v0.2.0 will replace each
// stub body with a typed call into google.golang.org/api/<svc>/v<n>.
//
// The generator targets Workspace-family typed-rest-sdk variants because they
// represent the densest cluster of routine reads/writes the dispatcher is
// asked to serve; coverage threshold of ≥50 satisfies bead gum-61d.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ehmo/gum/internal/catalog"
)

// WriteDispatchStubs emits one Go file per eligible variant under outDir.
// Existing files under outDir whose names match the generator naming convention
// are removed before regeneration so deleted variants do not leave orphan
// stubs behind. Returns the number of stub files written.
func WriteDispatchStubs(cat *catalog.Catalog, outDir string) (int, error) {
	if cat == nil {
		return 0, fmt.Errorf("dispatch stubs: nil catalog")
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return 0, fmt.Errorf("dispatch stubs: mkdir %s: %w", outDir, err)
	}

	// Sweep prior generated stubs so removed variants don't linger.
	entries, err := os.ReadDir(outDir)
	if err != nil {
		return 0, fmt.Errorf("dispatch stubs: read %s: %w", outDir, err)
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, "stub_") && strings.HasSuffix(name, ".go") {
			if err := os.Remove(filepath.Join(outDir, name)); err != nil {
				return 0, fmt.Errorf("dispatch stubs: remove %s: %w", name, err)
			}
		}
	}

	type emitted struct {
		opID, variantID, method, path string
	}
	var picks []emitted
	for _, op := range cat.Ops {
		for i := range op.Variants {
			v := &op.Variants[i]
			if v.BackendKind != catalog.BackendKindTypedRestSDK {
				continue
			}
			if v.InterfaceKind != catalog.InterfaceKindDiscoveryREST {
				continue
			}
			if v.Binding == nil || v.Binding.HTTP == nil {
				continue
			}
			if op.ServiceFamily != "workspace" {
				continue
			}
			picks = append(picks, emitted{
				opID:      op.OpID,
				variantID: v.VariantID,
				method:    v.Binding.HTTP.Method,
				path:      v.Binding.HTTP.Path,
			})
		}
	}
	// Deterministic order — both for reviewability and so the test that asserts
	// "≥50 files" inspects a stable surface.
	sort.Slice(picks, func(i, j int) bool { return picks[i].variantID < picks[j].variantID })

	for _, p := range picks {
		fileName := "stub_" + sanitizeIdent(p.variantID) + ".go"
		src, err := renderStub(p.opID, p.variantID, p.method, p.path)
		if err != nil {
			return 0, fmt.Errorf("dispatch stubs: render %s: %w", p.variantID, err)
		}
		if err := os.WriteFile(filepath.Join(outDir, fileName), src, 0o644); err != nil {
			return 0, fmt.Errorf("dispatch stubs: write %s: %w", fileName, err)
		}
	}
	return len(picks), nil
}

// sanitizeIdent maps a variant_id (e.g. "gmail.v1.rest.users.messages.list")
// to a filesystem-safe Go identifier ("gmail_v1_rest_users_messages_list").
// Non-alphanumeric runes collapse to '_' so paths stay portable on case-
// sensitive filesystems.
func sanitizeIdent(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// renderStub produces the gofmt'd source for one stub file.
func renderStub(opID, variantID, method, path string) ([]byte, error) {
	ident := sanitizeIdent(variantID)
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by cmd/gen-catalog. DO NOT EDIT.
//
// Variant: %s
// Op:      %s
// HTTP:    %s %s
//
// Forwards to internal/adapters.TypedRestSDK; context propagation is
// guaranteed by http.NewRequestWithContext within that adapter (spec §5.7).
package dispatch

import (
	"context"

	idispatch "github.com/ehmo/gum/internal/dispatch"
)

func stub_%s(ctx context.Context, inv *idispatch.Invocation, creds *idispatch.Credentials) (*idispatch.Response, error) {
	return executeREST(ctx, inv, creds, %q, %q, %q, %q)
}

func init() {
	Register(%q, stub_%s)
}
`, variantID, opID, method, path, ident, opID, variantID, method, path, variantID, ident)
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w", err)
	}
	return formatted, nil
}
