package dispatch

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sync"
	"time"

	"github.com/ehmo/gum/internal/fsatomic"
)

// AllowedPurposes is the closed enum of confirmation-token purposes.
// Any call to IssueToken with a purpose not in this list returns ErrUnknownPurpose.
var AllowedPurposes = []string{
	"delete",
	"move-to-trash",
	"replace",
	"bulk-update",
	"revoke-grant",
	"cancel",
	"external-share",
	"permanent",
}

// Sentinel errors for typed assertion in tests.
var (
	// ErrUnknownPurpose is returned by IssueToken when purpose is not in AllowedPurposes.
	ErrUnknownPurpose = errors.New("confirmation: unknown purpose")

	// ErrTokenAlreadyUsed is returned by ConsumeToken when the token has already been consumed.
	ErrTokenAlreadyUsed = errors.New("confirmation: token already used")

	// ErrTokenExpired is returned by ConsumeToken when the token's TTL has elapsed.
	ErrTokenExpired = errors.New("confirmation: token expired")

	// ErrPurposeMismatch is returned by ConsumeToken when the provided purpose does not
	// match the purpose the token was issued for.
	ErrPurposeMismatch = errors.New("confirmation: purpose mismatch")

	// ErrMalformedToken is returned by ConsumeToken when the token string is not a
	// well-formed confirmation token (e.g. not generated by IssueToken).
	ErrMalformedToken = errors.New("confirmation: malformed token")

	// ErrTokenStoreFull is returned by IssueToken when maxOutstanding tokens are
	// already outstanding and the store cannot accept a new one.
	ErrTokenStoreFull = errors.New("confirmation: token store full")
)

// allowedPurposesSet is the set form of AllowedPurposes for O(1) lookup.
var allowedPurposesSet map[string]bool

func init() {
	allowedPurposesSet = make(map[string]bool, len(AllowedPurposes))
	for _, p := range AllowedPurposes {
		allowedPurposesSet[p] = true
	}
}

// tokenFormatRe validates the HMAC token format: base64url(payload).base64url(hmac).
var tokenFormatRe = regexp.MustCompile(`^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$`)

// TokenRecord holds metadata for a single issued confirmation token.
type TokenRecord struct {
	Purpose    string
	IssuedAt   time.Time
	ExpiresAt  time.Time
	Used       bool
	KeyVersion int
}

// TokenStore is an in-memory confirmation-token registry backed by HMAC-SHA256.
// It is safe for concurrent use from a single process.
type TokenStore struct {
	records        map[string]TokenRecord
	mu             sync.Mutex
	maxOutstanding int
	defaultTTL     time.Duration
	keyDir         string
}

// NewTokenStore constructs a TokenStore with the given maximum number of
// outstanding (unspent) tokens, default TTL per token, and key directory.
// maxOutstanding must be > 0. defaultTTL must be > 0.
// keyDir is the directory where confirmation.key files are stored; it will be
// created on first IssueToken if it does not exist.
func NewTokenStore(maxOutstanding int, defaultTTL time.Duration, keyDir string) (*TokenStore, error) {
	return &TokenStore{
		records:        make(map[string]TokenRecord),
		maxOutstanding: maxOutstanding,
		defaultTTL:     defaultTTL,
		keyDir:         keyDir,
	}, nil
}

// tokenPayload is the JSON structure embedded in the token.
type tokenPayload struct {
	Purpose       string `json:"purpose"`
	IssuedAtUnix  int64  `json:"issued_at_unix"`
	ExpiresAtUnix int64  `json:"expires_at_unix"`
	Nonce         string `json:"nonce"`
	KeyVersion    int    `json:"key_version"`
}

// currentKeyVersion determines the current key version by counting versioned files
// in keyDir. Returns (version, error).
//
// Model: if no confirmation.key.N files exist, version = 1.
// Each confirmation.key.N file that exists adds 1 to version.
func (s *TokenStore) currentKeyVersion() (int, error) {
	entries, err := os.ReadDir(s.keyDir)
	if err != nil {
		if os.IsNotExist(err) {
			return 1, nil
		}
		return 0, err
	}
	count := 0
	for _, e := range entries {
		if matched, _ := filepath.Match("confirmation.key.*", e.Name()); matched {
			count++
		}
	}
	return count + 1, nil
}

// loadKeyForVersion loads key bytes for the given key version.
// Current version lives at confirmation.key; older version V lives at confirmation.key.<current - V>.
func (s *TokenStore) loadKeyForVersion(version int) ([]byte, error) {
	currentVersion, err := s.currentKeyVersion()
	if err != nil {
		return nil, err
	}
	var keyPath string
	if version == currentVersion {
		keyPath = filepath.Join(s.keyDir, "confirmation.key")
	} else {
		suffix := currentVersion - version
		keyPath = filepath.Join(s.keyDir, fmt.Sprintf("confirmation.key.%d", suffix))
	}
	data, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, err
	}
	if len(data) != 32 {
		return nil, fmt.Errorf("confirmation: key file %s has wrong length %d, expected 32", keyPath, len(data))
	}
	return data, nil
}

// ensureCurrentKey reads the current key from disk, generating it if missing.
// Returns (keyBytes, keyVersion, error).
func (s *TokenStore) ensureCurrentKey() ([]byte, int, error) {
	// Ensure keyDir exists.
	if err := os.MkdirAll(s.keyDir, 0o700); err != nil {
		return nil, 0, fmt.Errorf("confirmation: create key dir: %w", err)
	}

	keyPath := filepath.Join(s.keyDir, "confirmation.key")
	data, err := os.ReadFile(keyPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, 0, fmt.Errorf("confirmation: read key file: %w", err)
		}
		// Generate new 32-byte key.
		data = make([]byte, 32)
		if _, err := rand.Read(data); err != nil {
			return nil, 0, fmt.Errorf("confirmation: generate key: %w", err)
		}
		// Atomic write: a torn write here (truncated/0-byte key) would make the
		// len(data)!=32 guard below fail on every subsequent start, bricking all
		// destructive ops until the file is manually removed (review gum-yz76).
		if err := fsatomic.WriteFile(keyPath, data, 0o600); err != nil {
			return nil, 0, fmt.Errorf("confirmation: write key file: %w", err)
		}
	}
	if len(data) != 32 {
		return nil, 0, fmt.Errorf("confirmation: key file has wrong length %d, expected 32", len(data))
	}

	version, err := s.currentKeyVersion()
	if err != nil {
		return nil, 0, err
	}
	return data, version, nil
}

// signToken computes HMAC-SHA256 over payloadBytes using keyBytes.
func signToken(keyBytes, payloadBytes []byte) []byte {
	mac := hmac.New(sha256.New, keyBytes)
	mac.Write(payloadBytes)
	return mac.Sum(nil)
}

// IssueToken generates a new HMAC-signed confirmation token for the given purpose
// and adds it to the store. Returns ErrUnknownPurpose if purpose is not in
// AllowedPurposes. Returns ErrTokenStoreFull if the store already holds
// maxOutstanding tokens.
// The returned string has format base64url(payload).base64url(hmac).
func (s *TokenStore) IssueToken(purpose string) (string, error) {
	if !allowedPurposesSet[purpose] {
		return "", ErrUnknownPurpose
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if len(s.records) >= s.maxOutstanding {
		return "", ErrTokenStoreFull
	}

	// Ensure key exists and determine version (outside lock is fine since keyDir
	// operations are idempotent, but we're already holding the mu lock so that's OK).
	keyBytes, keyVersion, err := s.ensureCurrentKey()
	if err != nil {
		return "", err
	}

	// Generate 16-byte nonce, hex-encode to 32 chars.
	nonceBytes := make([]byte, 16)
	if _, err := rand.Read(nonceBytes); err != nil {
		return "", fmt.Errorf("confirmation: generate nonce: %w", err)
	}
	nonce := hex.EncodeToString(nonceBytes)

	now := time.Now()
	expiresAt := now.Add(s.defaultTTL)

	payload := tokenPayload{
		Purpose:       purpose,
		IssuedAtUnix:  now.Unix(),
		ExpiresAtUnix: expiresAt.Unix(),
		Nonce:         nonce,
		KeyVersion:    keyVersion,
	}

	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return "", fmt.Errorf("confirmation: marshal payload: %w", err)
	}

	sig := signToken(keyBytes, payloadBytes)

	enc := base64.RawURLEncoding
	payloadB64 := enc.EncodeToString(payloadBytes)
	sigB64 := enc.EncodeToString(sig)

	tok := payloadB64 + "." + sigB64

	s.records[tok] = TokenRecord{
		Purpose:    purpose,
		IssuedAt:   now,
		ExpiresAt:  expiresAt,
		Used:       false,
		KeyVersion: keyVersion,
	}

	return tok, nil
}

// ConsumeToken validates and atomically consumes the token, marking it as used.
//
// The purpose check is performed BEFORE HMAC verification per spec §6.1.2.
//
// Errors:
//   - ErrUnknownPurpose if purpose is not in AllowedPurposes.
//   - ErrMalformedToken if tok is not recognisable as a confirmation token.
//   - ErrTokenExpired if the token's TTL has elapsed.
//   - ErrPurposeMismatch if the token was issued for a different purpose.
//   - ErrTokenAlreadyUsed if the token has already been consumed.
func (s *TokenStore) ConsumeToken(tok, purpose string) error {
	// Step 1: Validate purpose BEFORE HMAC verify (spec §6.1.2).
	if !allowedPurposesSet[purpose] {
		return ErrUnknownPurpose
	}

	// Step 2: Match token against format regex.
	if !tokenFormatRe.MatchString(tok) {
		return ErrMalformedToken
	}

	// Step 3: Split and decode.
	dotIdx := -1
	for i := len(tok) - 1; i >= 0; i-- {
		if tok[i] == '.' {
			dotIdx = i
			break
		}
	}
	if dotIdx < 0 {
		return ErrMalformedToken
	}

	enc := base64.RawURLEncoding
	payloadPart := tok[:dotIdx]
	hmacPart := tok[dotIdx+1:]

	payloadBytes, err := enc.DecodeString(payloadPart)
	if err != nil {
		return ErrMalformedToken
	}
	sigBytes, err := enc.DecodeString(hmacPart)
	if err != nil {
		return ErrMalformedToken
	}

	// Step 4: Unmarshal payload.
	var payload tokenPayload
	if err := json.Unmarshal(payloadBytes, &payload); err != nil {
		return ErrMalformedToken
	}

	// Step 5: Look up key for payload.KeyVersion.
	keyBytes, err := s.loadKeyForVersion(payload.KeyVersion)
	if err != nil {
		return ErrMalformedToken
	}

	// Step 6: Verify HMAC (constant-time).
	expected := signToken(keyBytes, payloadBytes)
	if !hmac.Equal(expected, sigBytes) {
		return ErrMalformedToken
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	// Step 7: Check store record.
	record, ok := s.records[tok]
	if !ok {
		return ErrMalformedToken
	}

	// Step 8: Already used?
	if record.Used {
		return ErrTokenAlreadyUsed
	}

	// Step 9: Expired?
	if time.Now().After(record.ExpiresAt) {
		return ErrTokenExpired
	}

	// Step 10: Purpose mismatch?
	if record.Purpose != purpose {
		return ErrPurposeMismatch
	}

	// Step 11: Mark used.
	record.Used = true
	s.records[tok] = record

	return nil
}
